language: node_js
node_js:
  - '8'
before_install:
  - node -v
install:
  - npm install
cache: npm
notifications:
  slack:
    secure: fHmdTtDPNn2A/mph1QcYnGQnbP1rc6q09Mvp+/Lxaeeos/X73vLpsRHnbBrSH4iKlz+OPhPTst+FsV2YtPrZjUYI0/vEBMnznadJJ9fmryOEvADyqchgHF+MU8iQd4SJS83SJNd63SqyKF8tz/T6YIrj8FpAV2ZV0gZv179+Mc2WB64aj2RxRCXiRXpteJOR5lSf/tjGFah/XSufdQqVGXankM4ty2M8dJw3m6b33sO+WsEtTgTpZ9gnZik54d8iLiurtUeF1AZjzAMaMDad8VUryiAljwk+6q4p4MmPndjJH93mt+N+uWhuXb9nB2/+Mt7NgZJ0ySBLx7HpIYStvbw2qGY/e7805ohmNAQrZjXqwlTS84Zb49COsXDoGWu7L7jG4ZelDDpZ4TF8Otto3+DizZBOpiNqut60s+nfU6MEDNN092OqR0feleTySR1syObnYnfcNkHYpf/fdBjyfAa9IXCMVFZxOOXLSaOlBLaqr5mlVIWPRey5lYAJqviNWNFsV1U794ixKa0Azngf7KhDxc8zGG2ogQhzwemk0mcId4Qev9YASs1O6YbO6s99Kq+6vJoqHOezx0hExGppMw4bf6M7lPlF80u+hML2AMTImsyF3vQF4q9jRGxWHjC2tLo/q0ICkPwDYN2IuxfDVi4dT6njpYR86xESCNSYYZk=
after_success:
  - chmod +x ./deploy.sh
  - './deploy.sh'
