#branch-defaults:
#  master:
#    environment: todo-server
# (optional) Other branch-specific settings
# (e.g. if you want a staging environment)
#  master:
#    environment: mywebapp-api-staging
# branches:
#   only:
#     - develop
#     - master
global:
  application_name: todo-server
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Docker running on
    64bit Amazon Linux/2.11.0
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
